---
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: prod-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-2
spec:
  name: prod-lambda
  packageType: Image
  code:
    imageURI: 368763425814.dkr.ecr.us-east-2.amazonaws.com/prod/lambda:55d10c71
  role: arn:aws:iam::368763425814:role/prod-lambda-execution-role
  description: function created by ACK lambda-controller
  timeout: 300
  memorySize: 512
  environment:
    variables:
      S3_BUCKET_NAME: prod-app-output-files-368763425814
      DYNAMODB_TABLE_NAME: prod-pdf-files-per-user-descriptors
      ACCOUNT_ID: "368763425814"




